version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  frontend:
    build:
      dockerfile: apps/frontend/Dockerfile
      context: .
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_ENDPOINT: http://localhost:4000/api
    volumes:
      - ./:/app
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: apps/backend/Dockerfile
      context: .
    environment:
      NODE_ENV: development
      IS_LOCAL: true
      LOG_LEVEL: warn
      EXPOSE_DEBUG_INFO: true
      API_PORT: 4000
      DB_USER: andrew
      DB_PASSWORD: waterfast
      DB_NAME: radai
      DB_PORT: 5432
      DB_HOST: localhost
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - "4000:4000"

volumes:
  db_data:
